#!/bin/sh
# Description=socat as virtual serial port

#ExecStart=socat -d -d pty,link=/tmp/DEVTERM_PRINTER_OUT,raw,echo=0 pty,link=/tmp/DEVTERM_PRINTER_IN,raw,echo=0 
#ExecStartPost=/usr/local/bin/devterm_socat.sh

D="/sbin/start-stop-daemon --pidfile /var/run/devterm-printer-socat.pid"

case $1 in
	start)
		$D -b -m -S --exec /usr/bin/socat -- -d -d pty,link=/tmp/DEVTERM_PRINTER_OUT,raw,echo=0 pty,link=/tmp/DEVTERM_PRINTER_IN,raw,echo=0
		/usr/bin/devterm_socat_perms &
		;;
	stop)
		$D --stop
		;;
	restart)
		$D --restart
		;;
	*)
		echo "usage: $0 (start|stop|restart)" >&2
	;;
esac
