#!/bin/sh
#Description=devterm fan daemon

D="/sbin/start-stop-daemon --pidfile /var/run/devterm-fan-daemon.pid"

case $1 in
	start)
		$D -b -m -S --exec /usr/bin/temp_fan_daemon_a06.py
		;;
	stop)
		$D -K --remove-pidfile
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 (start|stop|restart)" >&2
	;;
esac
